kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    SDK_ACCOUNT:
      from_secret: sdk_account
    SA_MAIL:
      from_secret: sa_mail
  commands:
    - echo -E $${SDK_ACCOUNT} > credential.json
    - gcloud auth activate_service_account ${SA_MAIL} --key-file=credential.json
    # - rp_reviewdog src/
  when:
    event:
    - pull_request
