kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    CREDENTIAL_KEY:
      from_secret: cred_key
    SA_NAME:
      from_secret: sa_name
    PROJECT_ID:
      from_secret: project_id
    GSQL_REGION: us-central1
    GSQL_INSTANCE_NAME:
      from_secret: db_instance_name
    MYSQL_DATABASE:
      from_secret: db_name
    MYSQL_USER: boat_usr
    MYSQL_HOST: 127.0.0.1
  commands:
    - sleep 30
    - mysql -u test_boat_user -h testmysql --password=test_pw -D test_boat_db -e "show variables like 'character%'"
    # - mysql -u test_boat_user -h testmysql --password=test_pw -D test_boat_db -e "set character_set_database=utf8"
    # - mysql -u test_boat_user -h testmysql --password=test_pw -D test_boat_db -e "show variables like 'character%'"
    # - bash -c 'echo -E $${CREDENTIAL_KEY} > /tmp/credential.json'
    # - gcloud auth activate-service-account --key-file /tmp/credential.json
    # - gcloud config set project $PROJECT_ID
    # - export MYSQL_PASSWORD=$(gcloud secrets versions access latest --secret="mysql-usr-pw")
    # - make start_gdb
    - pipenv install --system
    - rp_pytest src/module/
    # あとで外す
    - mysql -u test_boat_user -h testmysql --password=test_pw -D test_boat_db -e "select * from jyo_master;"
    # - rp_reviewdog src/
    # - make down_gdb

  when:
    event:
    - pull_request

services:
- name: testmysql
  image: mysql:5.7
  # environment:
  #   MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  #   MYSQL_DATABASE: test_boat_db
  #   MYSQL_USER: 'test_boat_user'
  #   MYSQL_PASSWORD: 'test_pw'
  entrypoint: [ "mysqld" ]
  command: [ "--user=root", "--skip-grant-tables", "--character-set-server=utf8mb4" ]
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp=true --skip-character-set-client-handshake --character-set-filesystem=utf8
