kind: pipeline
type: docker
name: default

steps:
- name: reviewdog
  pull: always
  image: yashikab/mydog:python-dev
  environment:
    PRIVATE_KEY:
      from_secret: github_pri_key
    APP_ID:
      from_secret: app_id
    INSTALLATION_ID:
      from_secret: installation_id
    CLIENT_JSON:
      from_secret: client_json
  commands:
    - echo $${CLIENT_JSON} > credential.json
    - gcloud auth application-default login --client-id-file=credential.json --quiet
    # - rp_reviewdog src/
  when:
    event:
    - pull_request
